enableEmoji = true

[build]

  [[build.cachebusters]]
    source = "assets/notwatching/hugo_stats.json"
    target = "css"

  [[build.cachebusters]]
    source = "(postcss|tailwind).config.js"
    target = "css"

  [build.buildStats]
    enable = true

[security]
  [security.exec]
    # Keep Hugo defaults and add TailwindCSS binary so css.TailwindCSS can run.
    allow = [
      "^(dart-)?sass$",
      "^go$",
      "^git$",
      "^node$",
      "^postcss$",
      "^tailwindcss$",
    ]
