enableEmoji = true

[build]

  [[build.cachebusters]]
    source = "assets/notwatching/hugo_stats.json"
    target = "css"

  [[build.cachebusters]]
    source = "(postcss|tailwind).config.js"
    target = "css"

  [build.buildStats]
    enable = true
