version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    minor-and-patch:
      update-types:
        - "minor"
        - "patch"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/"
    minor-and-patch:
      update-types:
        - "minor"
        - "patch"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
