---
version: 2
updates:
  - directory: "/"
    groups:
      python-minor-and-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    package-ecosystem: "pip"
    schedule:
      day: "friday"
      interval: "weekly"
      time: "17:00"
      timezone: "America/Chicago"

  - directory: "/"
    groups:
      go-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    package-ecosystem: "gomod"
    schedule:
      day: "friday"
      interval: "weekly"
      time: "17:00"

      timezone: "America/Chicago"
  - directory: "/"
    groups:
      node-minor-and-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    package-ecosystem: "npm"
    schedule:
      day: "friday"
      interval: "weekly"
      time: "17:00"
      timezone: "America/Chicago"

  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      day: "friday"
      interval: "weekly"
      time: "17:00"
      timezone: "America/Chicago"
