changelog:
  exclude:
    labels:
      - ignore-changelog

  categories:
    - title: ":warning: Update considerations and deprecations"
      labels:
        - "type: breaking"
        - "type: deprecation"
        - "regression"
        - "type: revert"

    - title: ":rocket: New features and improvements"
      labels:
        - "type: feat"

    - title: ":lady_beetle: Bug fixes"
      labels:
        - "type: fix"

    - title: ":nail_polish: Style, UI, UX"
      labels:
        - "type: style"

    - title: ":book: Documentation"
      labels:
        - "type: docs"

    - title: ":hammer: Build/Test Dependency Upgrades"
      labels:
        - "dependencies"
        - "type: test"
        - "type: ci"
        - "type: build"
        - "type: chore"

    - title: ":question: What's Changed"
      labels:
        - "type: refactor"
