changelog:
  categories:
    - labels:
        - "type: breaking"
        - "type: deprecation"
        - "regression"
        - "type: revert"
      title: ":warning: Update considerations and deprecations"
    - labels:
        - "type: feat"
      title: ":rocket: New features and improvements"
    - labels:
        - "type: fix"
      title: ":lady_beetle: Bug fixes"
    - labels:
        - "type: style"
      title: ":nail_care: Style"
    - labels:
        - "type: docs"
      title: ":book: Documentation"
    - labels:
        - "dependencies"
        - "type: test"
        - "type: ci"
        - "type: build"
        - "type: chore"
      title: ":hammer: Build/Test Dependency Upgrades"
    - labels:
        - "type: refactor"
      title: ":question: What's Changed"
  exclude:
    labels:
      - ignore-changelog
