changelog:
  exclude:
    labels:
      - ignore-changelog

  categories:
    - title: ":question: What's Changed"
      labels:
        - "*"
      exclude:
        labels:
          - dependencies

    - title: ":tractor: Dependencies"
      labels:
        - dependencies
