[env]
  [env._]

    [env._.python]

      [env._.python.venv]
        create = true
        path   = ".venv"

[tools]
  pnpm          = "11.25.0"
  hugo-extended = "v0.165.0"
  node          = "22.23.0"
