demosite    = "https://esacteksab.com"
description = "An attempt at a barebones theme."
features    = ["dark", "tailwindcss", "dark-a11y"]
homepage    = "https://github.com/esacteksab/simpl"
license     = "MIT"
licenselink = "https://github.com/esacteksab/simpl/LICENSE"
name        = "simpl"
tags        = ["blog"]

[author]
  homepage = "https://esacteksab.com"
  name     = "Barry Morrison"
