name: Pre-Commit

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  SKIP: ${{ vars.SKIP }}

permissions:
  contents: read

jobs:
  precommit-reusable:
    uses: esacteksab/.github/.github/workflows/pre-commit.yml@1974c1790378cb8c665fabd34f8cc18a40653eef
